### ISSUE TITLE
Red X in the status line: ❌Saved

### ISSUE THREAD

**Issue by euu2021** [lilive/Freeplane-Bookmarks-add-on#7]
please, see https://github.com/freeplane/freeplane/discussions/744

**Comment by lilive** [comment]
Hi,
Hum... I'm sorry, I do not have the same behavior, and I have no clues !
The addon actually use the status line for messages, but it never display the message "Saved".

What Freeplane version do you use ?
Have you got the last version of the addon ?
If yes, you may help me to figure what's going on.

1 - This addon start a background task that watch to nodes changes, to prevent incorrect use of the addon icons by the user, and to ensure that these icons are always the first in a node icons list. I would like to know if the bug is related to this monitoring task. To disable this task, you have to temporary move the file freeplane_user_dir/scripts/init/BookmarksMonitorIcons.groovy to another place, and restart Freeplane. You will be able to use the addon without this task, and observe if this change something to the bug.

2 - Perhaps you can give me the minimal steps to reproduce the bug. Something like Open Freeplane / Create a new map / Create a node / Save the map (no bug) / Create a regular bookmark in the node / Save the map (here's the bug).

**Comment by euu2021** [comment]
Let me try to explain:

https://user-images.githubusercontent.com/77707706/225737651-a328cc87-6375-4f47-9a17-3e5e936e20fe.mp4



..

> To disable this task, you have to temporary move the file freeplane_user_dir/scripts/init/BookmarksMonitorIcons.groovy to another place, and restart Freeplane. 

 I don't have this script there. Is this the folder?

![image](https://user-images.githubusercontent.com/77707706/225736895-ba26ff1e-ad19-49d1-91af-43b1edeaa349.png)


Latest Bookmarks Add-on
Freeplane-Setup-with-Java-1.11.1-pre14

**Comment by lilive** [comment]
Thank you. Now I see the problem.

In fact, I do have the same behavior. But I haven't noticed it, because most of the time the displayed icon is a check mark next to the "Saved" message, and I thought it was the normal Freeplane behavior.

**Comment by lilive** [comment]
> I don't have this script there. Is this the folder?

Yes. It surprise me.

I do not use the preview version of Freeplane. Perhaps this version put the init addon scripts in another place, something like the `addons\bookmarks\scripts\init` folder. Anyway, if the addon works for you this is OK. Can you add or delete the green bookmark icon with the Freeplane icon toolbar (you can find this icon with others user icons) ?

![toolbar](https://user-images.githubusercontent.com/2719976/225883140-23a6ce67-8ef9-40d2-9edb-5d77b115354c.png)

Normally you can't, this is one of the purpose of the monitoring task.

BTW, I know that this is not a very good solution to lock the usage of this icon, but it was the simplest.

**Comment by euu2021** [comment]
> Can you add or delete the green bookmark icon with the Freeplane icon toolbar (you can find this icon with others user icons) ?

Yes, I can.

Probably, I accidentally deleted the init script, at some moment. I remember that, some months ago, I was messing around with init scripts, so I may have deleted it then.

**Comment by lilive** [comment]
OK. If you want to restore it, you can reinstall the addon (I should release really soon an update with the bug fix). 
The monitoring task do another thing : it ensure that a bookmark icon is always the first icon, when a node had several ones.

**Comment by lilive** [comment]
Done !

https://github.com/lilive/Freeplane-Bookmarks-add-on/releases/tag/v0.7.3

**Comment by euu2021** [comment]
Now, it's working fine. And the init script appeared again, as I reinstalled the script:

![image](https://user-images.githubusercontent.com/77707706/226146737-2db07885-dffa-46c1-8e2d-43772f8eccbb.png)
